"""
KitchenXpert AI Models Package.
"""

from .kitchen import (
    MeasurementUnit,
    KitchenShape,
    KitchenStyle,
    ObstacleType,
    UtilityType,
    CabinetType,
    ApplianceCategory,
    WallDirection,
    RoomDimensions,
    WallObstacle,
    WallSegment,
    UtilityConnection,
    RoomConfiguration,
    ProductDimensions,
    CatalogProduct,
    Position3D,
    PlacedItem,
    ColorPreferences,
    AccessibilityRequirements,
    BudgetRange,
    UserPreferences,
    GenerationConstraints,
    PricingSummary,
    ConfigurationScore,
    ValidationError,
    ValidationWarning,
    ValidationResult,
    KitchenConfiguration,
    GenerationRequest,
    GenerationStats,
    GenerationResponse,
)

from .recommendations import (
    RecommendationConfidence,
    StyleCategory,
    BudgetCategory,
    SpaceZone,
    StyleFeature,
    StyleMatch,
    StylePreferenceInput,
    StyleRecommendationRequest,
    StyleRecommendation,
    StyleRecommendationResponse,
    BudgetAllocation,
    ProductAlternative,
    BudgetOptimizationRequest,
    BudgetSavingOpportunity,
    BudgetOptimizationResult,
    WorkTriangle,
    LayoutZone,
    LayoutOptimizationRequest,
    LayoutOptimizationResult,
    SpaceUtilization,
    StorageCapacity,
    AccessibilityAnalysis,
    SpaceConflict,
    SpaceAnalysisRequest,
    WorkflowAnalysis,
    SpaceAnalysisResult,
)

__all__ = [
    # Kitchen enums
    "MeasurementUnit",
    "KitchenShape",
    "KitchenStyle",
    "ObstacleType",
    "UtilityType",
    "CabinetType",
    "ApplianceCategory",
    "WallDirection",
    # Kitchen models
    "RoomDimensions",
    "WallObstacle",
    "WallSegment",
    "UtilityConnection",
    "RoomConfiguration",
    "ProductDimensions",
    "CatalogProduct",
    "Position3D",
    "PlacedItem",
    "ColorPreferences",
    "AccessibilityRequirements",
    "BudgetRange",
    "UserPreferences",
    "GenerationConstraints",
    "PricingSummary",
    "ConfigurationScore",
    "ValidationError",
    "ValidationWarning",
    "ValidationResult",
    "KitchenConfiguration",
    "GenerationRequest",
    "GenerationStats",
    "GenerationResponse",
    # Recommendation enums
    "RecommendationConfidence",
    "StyleCategory",
    "BudgetCategory",
    "SpaceZone",
    # Style recommendations
    "StyleFeature",
    "StyleMatch",
    "StylePreferenceInput",
    "StyleRecommendationRequest",
    "StyleRecommendation",
    "StyleRecommendationResponse",
    # Budget optimization
    "BudgetAllocation",
    "ProductAlternative",
    "BudgetOptimizationRequest",
    "BudgetSavingOpportunity",
    "BudgetOptimizationResult",
    # Layout optimization
    "WorkTriangle",
    "LayoutZone",
    "LayoutOptimizationRequest",
    "LayoutOptimizationResult",
    # Space analysis
    "SpaceUtilization",
    "StorageCapacity",
    "AccessibilityAnalysis",
    "SpaceConflict",
    "SpaceAnalysisRequest",
    "WorkflowAnalysis",
    "SpaceAnalysisResult",
]
