#!/usr/bin/env bash
# =============================================================================
# generate-secrets.sh — KitchenXpert production secret generator
# -----------------------------------------------------------------------------
# Prints a ready-to-paste block of cryptographically-strong secrets for every
# variable flagged CHANGE_ME in `.env.production.example`.
#
# Design choices:
#   - Pure stdout. NOTHING is written to disk, so the script is safe to run
#     on a developer laptop, in CI logs that scrub output, or pipe through
#     `pbcopy` / `xclip`.
#   - Uses `openssl` (already a dependency of every CI image we ship) and
#     falls back to `/dev/urandom` if openssl is unavailable.
#   - Each secret is generated independently — no shared seed.
# =============================================================================

set -euo pipefail

# ---------- helpers -----------------------------------------------------------

require_random() {
  if ! command -v openssl >/dev/null 2>&1; then
    if [ ! -r /dev/urandom ]; then
      echo "ERROR: neither 'openssl' nor /dev/urandom is available" >&2
      exit 1
    fi
  fi
}

# rand_base64 N   → base64-encode N random bytes (no newline)
rand_base64() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 "$bytes" | tr -d '\n'
  else
    head -c "$bytes" /dev/urandom | base64 | tr -d '\n'
  fi
}

# rand_hex N      → hex-encode N random bytes (no newline)
rand_hex() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes" | tr -d '\n'
  else
    head -c "$bytes" /dev/urandom | xxd -p -c 256 | tr -d '\n'
  fi
}

# ---------- main --------------------------------------------------------------

require_random

cat <<'EOF'
# -----------------------------------------------------------------------------
# Generated by scripts/generate-secrets.sh on
EOF
echo "#   $(date -u +'%Y-%m-%dT%H:%M:%SZ')   (host: $(hostname))"
cat <<'EOF'
#
# Paste these lines into your `.env.production` file (or, better, into the
# secret store of your hosting provider — OVH Vault, Scaleway Secret Manager,
# Doppler, 1Password Secrets Automation, etc.).
#
# All secrets below are independent. Rotating one does not invalidate the
# others. Treat every value as a top-tier credential.
# -----------------------------------------------------------------------------

EOF

printf 'JWT_ACCESS_SECRET=%s\n'      "$(rand_base64 64)"
printf 'JWT_REFRESH_SECRET=%s\n'     "$(rand_base64 64)"
printf 'DATA_ENCRYPTION_KEY=%s\n'    "$(rand_hex 32)"
printf 'INTERNAL_API_KEY=%s\n'       "$(rand_base64 48)"

cat <<'EOF'

# -----------------------------------------------------------------------------
# Optional but recommended additional secrets:
# -----------------------------------------------------------------------------
EOF
printf 'CSRF_SECRET=%s\n'            "$(rand_base64 48)"
printf 'SESSION_SECRET=%s\n'         "$(rand_base64 48)"
printf 'SCRAPER_BRIDGE_TOKEN=%s\n'   "$(rand_base64 48)"

cat <<'EOF'

# -----------------------------------------------------------------------------
# DO NOT redirect this output to a file in your repository.
# Recommended workflow:
#
#   bash scripts/generate-secrets.sh | pbcopy            # macOS
#   bash scripts/generate-secrets.sh | xclip -selection clipboard   # Linux
#   bash scripts/generate-secrets.sh | wl-copy           # Wayland
#
# Then paste into your secret manager. Verify the resulting environment
# with:  bash scripts/preflight-check.sh
# -----------------------------------------------------------------------------
EOF
