#!/bin/bash
#
# Setup Test Environment - KitchenXpert
#
# Sets up isolated test environment for integration testing.
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Configuration
TEST_ENV="${TEST_ENV:-test}"
TEST_DB_NAME="${TEST_DB_NAME:-kitchenxpert_test}"
TEST_MONGODB_NAME="${TEST_MONGODB_NAME:-kitchenxpert_test}"
DOCKER_COMPOSE_FILE="${DOCKER_COMPOSE_FILE:-$PROJECT_ROOT/docker-compose.test.yml}"
USE_DOCKER="${USE_DOCKER:-true}"
SEED_DATA="${SEED_DATA:-true}"

# Logging
log() {
    local level=$1
    local message=$2
    case $level in
        "INFO")    echo -e "${BLUE}[TEST-ENV]${NC} $message" ;;
        "SUCCESS") echo -e "${GREEN}[TEST-ENV]${NC} $message" ;;
        "WARNING") echo -e "${YELLOW}[TEST-ENV]${NC} $message" ;;
        "ERROR")   echo -e "${RED}[TEST-ENV]${NC} $message" ;;
        "STEP")    echo -e "${CYAN}[STEP]${NC} $message" ;;
    esac
}

print_header() {
    echo ""
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║${NC}      KitchenXpert - Test Environment Setup                 ${BLUE}║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

check_prerequisites() {
    log "STEP" "Checking prerequisites..."

    local required_tools=("node" "pnpm")
    local missing_tools=()

    for tool in "${required_tools[@]}"; do
        if ! command -v $tool &> /dev/null; then
            missing_tools+=($tool)
        fi
    done

    if [ "$USE_DOCKER" = "true" ]; then
        if ! command -v docker &> /dev/null; then
            missing_tools+=("docker")
        fi
        if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
            missing_tools+=("docker-compose")
        fi
    fi

    if [ ${#missing_tools[@]} -gt 0 ]; then
        log "ERROR" "Missing required tools: ${missing_tools[*]}"
        exit 1
    fi

    log "SUCCESS" "Prerequisites check passed"
}

create_env_file() {
    log "STEP" "Creating test environment file..."

    local env_file="$PROJECT_ROOT/.env.test"

    cat > "$env_file" << EOF
# Test Environment Configuration
# Generated by setup-test-environment.sh

NODE_ENV=test
APP_ENV=test

# Database
DATABASE_URL=postgresql://postgres:postgres@localhost:5433/$TEST_DB_NAME?schema=public
MONGODB_URI=mongodb://localhost:27018/$TEST_MONGODB_NAME

# Redis
REDIS_URL=redis://localhost:6380

# Auth
JWT_ACCESS_SECRET=test-access-secret-key-for-testing-only
JWT_REFRESH_SECRET=test-refresh-secret-key-for-testing-only
SESSION_SECRET=test-session-secret-key-for-testing

# API
API_BASE_URL=http://localhost:3001
FRONTEND_URL=http://localhost:3000
PARTNER_PORTAL_URL=http://localhost:3002

# Testing
TEST_TIMEOUT=30000
ENABLE_TEST_LOGGING=true
MOCK_EXTERNAL_SERVICES=true

# Email (Mock)
SMTP_HOST=localhost
SMTP_PORT=1025
SMTP_USER=test
SMTP_PASS=test

# Storage (Mock)
STORAGE_PROVIDER=local
STORAGE_PATH=$PROJECT_ROOT/test-uploads

# AI Services (Mock)
AI_SERVICE_URL=http://localhost:3003
MOCK_AI_RESPONSES=true
EOF

    chmod 600 "$env_file"
    log "SUCCESS" "Created test environment file: $env_file"
}

start_docker_services() {
    log "STEP" "Starting Docker test services..."

    # Create docker-compose.test.yml if it doesn't exist
    if [ ! -f "$DOCKER_COMPOSE_FILE" ]; then
        log "INFO" "Creating Docker Compose test configuration..."

        cat > "$DOCKER_COMPOSE_FILE" << EOF
version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: kitchenxpert_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: $TEST_DB_NAME
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb-test:
    image: mongo:6
    container_name: kitchenxpert_mongodb_test
    ports:
      - "27018:27017"
    volumes:
      - mongodb_test_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    container_name: kitchenxpert_redis_test
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: kitchenxpert_mailhog_test
    ports:
      - "1025:1025"
      - "8026:8025"

volumes:
  postgres_test_data:
  mongodb_test_data:
EOF
    fi

    # Start services
    if docker compose version &> /dev/null; then
        docker compose -f "$DOCKER_COMPOSE_FILE" up -d
    else
        docker-compose -f "$DOCKER_COMPOSE_FILE" up -d
    fi

    log "INFO" "Waiting for services to be healthy..."
    sleep 10

    # Wait for PostgreSQL
    local retries=30
    while [ $retries -gt 0 ]; do
        if docker exec kitchenxpert_postgres_test pg_isready -U postgres &> /dev/null; then
            break
        fi
        retries=$((retries - 1))
        sleep 1
    done

    if [ $retries -eq 0 ]; then
        log "ERROR" "PostgreSQL failed to start"
        exit 1
    fi

    log "SUCCESS" "Docker test services started"
}

setup_database() {
    log "STEP" "Setting up test database..."

    cd "$PROJECT_ROOT"

    # Load test environment
    export $(grep -v '^#' .env.test | xargs)

    # Run Prisma migrations
    if [ -f "prisma/schema.prisma" ]; then
        log "INFO" "Running Prisma migrations..."
        pnpm prisma migrate deploy --schema=prisma/schema.prisma 2>/dev/null || \
        pnpm prisma db push --schema=prisma/schema.prisma --accept-data-loss 2>/dev/null || true

        log "INFO" "Generating Prisma client..."
        pnpm prisma generate --schema=prisma/schema.prisma 2>/dev/null || true
    fi

    log "SUCCESS" "Test database setup complete"
}

seed_test_data() {
    log "STEP" "Seeding test data..."

    cd "$PROJECT_ROOT"

    # Load test environment
    export $(grep -v '^#' .env.test | xargs)

    # Run test data generator
    if [ -f "$SCRIPT_DIR/generate-test-data.js" ]; then
        node "$SCRIPT_DIR/generate-test-data.js"
    elif [ -f "prisma/seed.ts" ]; then
        pnpm prisma db seed 2>/dev/null || true
    fi

    log "SUCCESS" "Test data seeded"
}

setup_test_uploads() {
    log "STEP" "Setting up test upload directory..."

    local upload_dir="$PROJECT_ROOT/test-uploads"
    mkdir -p "$upload_dir"/{images,documents,temp}

    # Create sample test files
    echo "Test image placeholder" > "$upload_dir/images/.gitkeep"
    echo "Test document placeholder" > "$upload_dir/documents/.gitkeep"

    log "SUCCESS" "Test upload directory ready"
}

verify_environment() {
    log "STEP" "Verifying test environment..."

    local issues=0

    # Check PostgreSQL connection
    if [ "$USE_DOCKER" = "true" ]; then
        if docker exec kitchenxpert_postgres_test pg_isready -U postgres &> /dev/null; then
            log "SUCCESS" "PostgreSQL: Connected"
        else
            log "ERROR" "PostgreSQL: Not available"
            ((issues++))
        fi

        # Check MongoDB connection
        if docker exec kitchenxpert_mongodb_test mongosh --eval "db.adminCommand('ping')" &> /dev/null; then
            log "SUCCESS" "MongoDB: Connected"
        else
            log "ERROR" "MongoDB: Not available"
            ((issues++))
        fi

        # Check Redis connection
        if docker exec kitchenxpert_redis_test redis-cli ping &> /dev/null; then
            log "SUCCESS" "Redis: Connected"
        else
            log "ERROR" "Redis: Not available"
            ((issues++))
        fi
    fi

    # Check environment file
    if [ -f "$PROJECT_ROOT/.env.test" ]; then
        log "SUCCESS" "Environment file: Present"
    else
        log "ERROR" "Environment file: Missing"
        ((issues++))
    fi

    if [ $issues -gt 0 ]; then
        log "ERROR" "Environment verification failed with $issues issue(s)"
        return 1
    fi

    log "SUCCESS" "Environment verification passed"
    return 0
}

print_summary() {
    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║${NC}        Test Environment Ready                              ${GREEN}║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "  Environment: $TEST_ENV"
    echo "  PostgreSQL:  localhost:5433 (DB: $TEST_DB_NAME)"
    echo "  MongoDB:     localhost:27018 (DB: $TEST_MONGODB_NAME)"
    echo "  Redis:       localhost:6380"
    echo "  MailHog:     http://localhost:8026"
    echo ""
    echo "  To run tests:"
    echo "    pnpm test:integration"
    echo ""
    echo "  To cleanup:"
    echo "    ./scripts/integration-tests/cleanup-test-environment.sh"
    echo ""
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --no-docker)
            USE_DOCKER="false"
            shift
            ;;
        --no-seed)
            SEED_DATA="false"
            shift
            ;;
        --db-name)
            TEST_DB_NAME="$2"
            shift 2
            ;;
        --help)
            echo "Usage: setup-test-environment.sh [options]"
            echo ""
            echo "Options:"
            echo "  --no-docker      Don't use Docker (use existing services)"
            echo "  --no-seed        Don't seed test data"
            echo "  --db-name <name> Custom test database name"
            echo "  --help           Show this help message"
            exit 0
            ;;
        *)
            log "ERROR" "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Main execution
print_header
check_prerequisites
create_env_file

if [ "$USE_DOCKER" = "true" ]; then
    start_docker_services
fi

setup_database

if [ "$SEED_DATA" = "true" ]; then
    seed_test_data
fi

setup_test_uploads
verify_environment
print_summary
